### ISSUE TITLE
It doesn't work when set #define TINY_GSM_RX_BUFFER 1024

### ISSUE THREAD

**Issue by yuzukihironaka-lefixea** [alkonosst/SSLClient#9] opened 2023-10-02 08:47 UTC
Hello @alkonosst ,

First of all Thanks for your work!

I have an issue about SSL connection.

**Describe the error**

When I use with TinyGsm and defned `#define TINY_GSM_RX_BUFFER 1024`, ESP32 throws exception.

**To reproduce it**
1. set some Client

```cpp
TinyGsmClient base_client(modem, 0);
SSLClientESP32 sslclient(&base_client);
PubSubClient mqtt;
```

2. set certificates

```cpp
mqtt.setClient(sslclient);
sslclient.setCACert(rootca);
sslclient.setCertificate(certificate);
sslclient.setPrivateKey(privatekey);
```
3. connect to broker

```cpp
mqtt.connect(devicename);
```

**Expected behavior**
success to connect

**Screenshots**
<img width="432" alt="image" src="https://github.com/alkonosst/SSLClientESP32/assets/107729799/34ee72ad-bcee-412e-9bb0-db147baa0a92">

<img width="612" alt="image" src="https://github.com/alkonosst/SSLClientESP32/assets/107729799/2e23d02b-4807-4cb3-9d75-8cbb616778d0">

**Please complete the following information:**
- Hardware: ESP32 + SIM7500JC
- SSLClient version: v2.0.0
- Broker: AWS IoT Core

**Additional context**

It works fine when defined `#define TINY_GSM_RX_BUFFER 64`.
But it also doesn't work any other Buffer Size (higher than 64 byte).

I couldn't solve this by myself so I really want help ;(

Thanks in advance!

**Comment by alkonosst** [comment] 2023-10-06 15:34
Hi @yuzukihironaka-lefixea, I'm sorry, I've only a SIM7600G-H to try to reproduce your error. I don't have any trouble defining `TINY_GSM_RX_BUFFER` to `1024` (I've been using 1024 in a lot of projects).

Your program is crashing at the following line:
https://github.com/alkonosst/SSLClientESP32/blob/fcecf1c0322994fb55692ef6cc984e9a6cbaf642/src/ssl_client.cpp#L298C71-L298C71

That exception is because the CPU is loading a illegal address (maybe a null pointer?). I don't know for sure. If `&ssl_client->ssl_ctx` would have been null, the `start_ssl_client` would have returned before `mbedtls_ssl_handshake`.

Please consider the following:
- Can you provide more context? e.g.: TinyGSM connection to network, definition of credentials (hide the keys).
- Can you enable TinyGSM debug? You need to define this line before including that library: `#define TINY_GSM_DEBUG Serial`. Maybe there is something happening with the SIM7000 communication.

**Comment by yuzukihironaka-lefixea** [comment] 2023-10-11 07:28
@alkonosst Thank you for the reply!

The pointer's problem might have been due to a Global definition of TinyGsmClient, I'm not sure.

There are some `TinyGsmClient` object and defined as global in my code. One of client is used in other function except `setup()` and `loop()`.

- in main.cpp
```cpp
// global definitions
TinyGsm modem(SerialAT);
TinyGsmClient base_client(modem, 0);
TinyGsm clientForOTA(modem, 1);
// ↑ this object
SSLClientESP32 sslclient(&base_client);
PubSubClient mqtt;
...
```

- in other function (defined in other file)
```cpp
bool FwUpdate(const bool& enabled) {
  ...
  e.g. clientForOTA.print(request);
  // ↑ using global client object here.
}
```

Therefore, I changed following : 

- in main.cpp
```cpp
// global definitions
TinyGsm modem(SerialAT);
TinyGsmClient base_client(modem, 0);
// TinyGsm clientForOTA(modem, 1);
// ↑ undefine
SSLClientESP32 sslclient(&base_client);
PubSubClient mqtt;
...
```

- in other function (defined in other file)
```cpp
bool FwUpdate(const bool& enabled) {
  TinyGsm modemForOTA(SerialAT);
  TinyGsmClient clientForOTA(modemForOTA, 1);
  ...
  e.g. clientForOTA.print(request); 
}
```

The ESP32 is not rebooting in this case, I don't know why it's getting fixed.

Anyway, I can connect to my broker now. Thank you for your advice!

But after a connecting, sometimes failed to connect.

```
[ 65903][W][main.cpp:701] loop(): [MQTT] Broker Server disconnected
[ 65904][D][SSLClientESP32.cpp:113] connect(): Connecting to a2s****-ats.iot.ap-northeast-1.amazonaws.com:8883
[ 65905][I][ssl_client.cpp:158] start_ssl_client(): Connecting to a2s****-ats.iot.ap-northeast-1.amazonaws.com:8883
[ 81176][E][ssl_client.cpp:35] _handle_error(): [start_ssl_client():300]: (-9058) X509 - The algorithm tag or value is invalid : ASN1 - ASN1 tag was of an unexpected value
```

It isn't every single time, It can be successfull.
````
[ 81335][W][main.cpp:701] loop(): [MQTT] Broker Server disconnected
[ 81335][D][SSLClientESP32.cpp:113] connect(): Connecting to a2s****-ats.iot.ap-northeast-1.amazonaws.com:8883
[ 81336][I][ssl_client.cpp:158] start_ssl_client(): Connecting to a2s****-ats.iot.ap-northeast-1.amazonaws.com:8883
[ 82907][D][ssl_client.cpp:309] start_ssl_client(): Protocol is TLSv1.2 Ciphersuite is TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
[ 82908][D][ssl_client.cpp:311] start_ssl_client(): Record expansion is 29
[ 82910][I][SSLClientESP32.cpp:125] connect(): SSL connection established
[ 82911][D][ssl_client.cpp:394] send_ssl_data(): Writing SSL (26 bytes)...
````

I'm reading credentials from SD card : 
```cpp
      FsFile entry = root.openNextFile();
      if (!entry) break;
      if (!entry.isDirectory()) {
        String filename;
        char tmp[100];
        entry.getName(tmp, 100);
        filename = String(tmp);
        ESP_LOGI("Config", "found config file : ");
        ESP_LOGI("Config", "%s", filename.c_str());
        String path = "/config/" + filename;
        String contents = "";
        readFile(path.c_str(), &contents);
        if (filename.endsWith(".pem")) {
          this->ssl.rootca = contents;
          ESP_LOGI("Config", "SSL : set %s\n", filename.c_str());
        } else if (filename.endsWith(".crt")) {
          this->ssl.certificate = contents;
          ESP_LOGI("Config", "SSL : set %s\n", filename.c_str());
        } else if (filename.endsWith(".key")) {
          this->ssl.privatekey = contents;
          ESP_LOGI("Config", "SSL : set %s\n", filename.c_str());
        }
      }
--------------
// ssl member is defined as struct : 
struct SSL {
  String rootca;
  String certificate;
  String privatekey;
};
--------------
```

and then call `setCACert(), setCertificate(), setPrivateKey()` : 
```cpp
        sslclient.setCACert(config.ssl.rootca.c_str());
        sslclient.setCertificate(config.ssl.certificate.c_str());
        sslclient.setPrivateKey(config.ssl.privatekey.c_str());
        mqtt.setClient(sslClient);
        if (!mqtt.connect(config.mqtt.devicename.c_str())) {
          ESP_LOGW("MQTT", "Connect to Broker failed");
        } else {
          ESP_LOGI("MQTT", " success");
        }
```

TinyGSM connection to network : 
```cpp
    do {
      ESP_LOGI("LTE", "Waiting for network...");
      if (!modem.waitForNetwork(10000L, true)) {
        ESP_LOGW("LTE", "Network Connect failed");
        ESP_LOGW("LTE", "trying APN setting");
        String send_cmd = "AT+CGDCONT=1,\"IP\",\"" + config.lte.apn + "\"";
        SerialAT.println(send_cmd);
        modem.waitResponse();
        send_cmd = "AT+CGAUTH=1,3,\"" + config.lte.pass + "\",\"" +
                   config.lte.username + "\"";
        SerialAT.println(send_cmd);
        modem.waitResponse();
        SerialAT.println("AT+CFUN=0");
        modem.waitResponse();
        SerialAT.println("AT+CFUN=1");
        modem.waitResponse();
        delay(10000);
        ESP_LOGW("LTE", "APN setting is done.");
      }
    } while (!modem.isNetworkConnected());
    ESP_LOGI("LTE", " success");

    if (modem.isNetworkConnected()) {
      ESP_LOGI("LTE", "Network connected");
    }

    // GPRS connection parameters are usually set after network registration
    ESP_LOGI("LTE", "Connecting to  %s", config.lte.apn.c_str());
    if (!modem.gprsConnect(config.lte.apn.c_str(),
                           config.lte.username.c_str(),
                           config.lte.pass.c_str())) {
      ESP_LOGW("LTE", "GPRS : Connect failed");
    } else {
      ESP_LOGI("LTE", " success");
    }

    if (modem.isGprsConnected()) {
      ESP_LOGI("LTE", "GPRS connected");
    }
````

MQTT reconnecting  : 
```cpp
      if (config.lte.enabled && config.mqtt.enabled &&
          modem.isNetworkConnected()) {
        if (!mqtt.connected()) {
          ESP_LOGW("MQTT", "Broker Server disconnected");
          color = led_colors::YELLOW;
          xQueueSend(xQueueNetwork, &color, 0);
          if (!mqtt.connect(config.mqtt.devicename.c_str())) {
            ESP_LOGW("MQTT", "Couldn't reconnect to Server");
          } else {
            ESP_LOGW("MQTT", "Broker Server reconnected");
        }
      }
````

If define `TINY_GSM_RX_BUFFER 64`, it works fine, so it is unlikely that there is something wrong with credentials.

And I also defined `TINY_GSM_DEBUG Serial` but I couldn't obtain useful information.

I appreciate your reading.

**Comment by alkonosst** [comment] 2023-10-12 15:44
I'm glad there is some progress now! 

I suggest you keep the `TinyGsm` object global. That is the instance for the hardware (modem), and you don't need to instance another object is there isn't another physical modem.

Also, can you try your code with the [latest release](https://github.com/alkonosst/SSLClientESP32/releases/tag/v2.0.1)? To see if there is a difference (*fixed local `TinyGsmClient` objects*).

Finally, a little personal advice: try to keep the data flow between the modem **thread-safe**, i.e use traffic with client 1, finish traffic with client 1, then initiate traffic with client 2, and later finish traffic with client 2, and so on. I had some troubles using FreeRTOS and TinyGsm in the past. Hope it helps somehow.

**Comment by yuzukihironaka-lefixea** [comment] 2023-10-13 09:08
I've just tried with `v2.0.1`, there was no differences.

Anyway, I think it's getting close to solve.  I also using `FreeRTOS`, so I'm going to check about that.

I will report back if I find something regarding `SSLClientESP32`.

Thank you so much!

**Comment by alkonosst** [comment] 2023-10-13 13:56
Good to read that :)

Closing by now, let me know if you find some issue again.

**Closed as completed by alkonosst** 2023-10-13 13:56 UTC
Labels: bug

**Comment by WebDust21** [comment] 2024-02-26 15:31
> If define `TINY_GSM_RX_BUFFER 64`, it works fine, so it is unlikely that there is something wrong with credentials.

I ran down the same rabbit trail, and at least for me the problem was that the Serial module's FIFO buffer defaults to 256 bytes in the ESP32.  This results in a hang in TinyGSM when it's expecting to read 1024 bytes, but there's only 256 bytes in the serial FIFO--and the other 768 bytes have been lost.
The solution in my case was to set the Serial RX FIFO to a bit larger than the TinyGSM buffer to ensure that it would never run out, as in:
```
Serial.setRxBufferSize(TINY_GSM_RX_BUFFER * 1.2);
```

Worked wonders...

EDIT: In my case it wasn't crashing--but I also have specified a TinyGSM delay to prevent WDT crash resets, as in:
```
#define TINY_GSM_YIELD_MS       2
```
It'd just hang for a minute at a time in the handshake.  Server would get bored and close the connection.

**Comment by alkonosst** [comment] 2024-02-26 16:10
Excellent @WebDust21 , that would be a possible solution for the initial issue of @yuzukihironaka-lefixea.
